name: pokedex
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^1.0.4
  flutter_svg: ^1.1.6
  http: ^0.13.5
  lottie: ^1.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/lottie/
